// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsaMDql-y0mnjla-WhDy_kN4BYt-33GRI',
    appId: '1:705871068180:web:57ae32b448e1c312c33b01',
    messagingSenderId: '705871068180',
    projectId: 'bundy-track-87a2a',
    authDomain: 'bundy-track-87a2a.firebaseapp.com',
    storageBucket: 'bundy-track-87a2a.appspot.com',
    measurementId: 'G-CPWDN5MGK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkQDxrvkRHXsu_GRc5QWkKUdGMa28rghA',
    appId: '1:705871068180:android:7b4b39f646eeefddc33b01',
    messagingSenderId: '705871068180',
    projectId: 'bundy-track-87a2a',
    storageBucket: 'bundy-track-87a2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChXblJy3n7Pn8y7GZzDcAmfUpAVfVLz08',
    appId: '1:705871068180:ios:02f882c77fc70ad7c33b01',
    messagingSenderId: '705871068180',
    projectId: 'bundy-track-87a2a',
    storageBucket: 'bundy-track-87a2a.appspot.com',
    iosBundleId: 'com.example.bundyTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChXblJy3n7Pn8y7GZzDcAmfUpAVfVLz08',
    appId: '1:705871068180:ios:02f882c77fc70ad7c33b01',
    messagingSenderId: '705871068180',
    projectId: 'bundy-track-87a2a',
    storageBucket: 'bundy-track-87a2a.appspot.com',
    iosBundleId: 'com.example.bundyTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsaMDql-y0mnjla-WhDy_kN4BYt-33GRI',
    appId: '1:705871068180:web:6053f46ab8e46e3cc33b01',
    messagingSenderId: '705871068180',
    projectId: 'bundy-track-87a2a',
    authDomain: 'bundy-track-87a2a.firebaseapp.com',
    storageBucket: 'bundy-track-87a2a.appspot.com',
    measurementId: 'G-VF0PKCS2NQ',
  );
}
